# modeltest_loop.sub
###
universe = vanilla
log = modeltest_$(Cluster).log
error = modeltest_$(Cluster)_$(df).err
output = modeltest_$(Cluster)_$(df).out
#
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = $(df),modeltest_install.tar.gz
#
executable = modeltest.sh
#
arguments = $(df)
#
request_cpus = 16
request_memory = 5GB
request_disk = 3GB
getenv=true
#
queue df from aln_list2.txt

